/*
 * Progreso.java
 *
 * Created on 11 de noviembre de 2004, 11:52
 */

package xcx;
import java.util.*;
import java.io.*;
import java.awt.*;
/**
 *
 * @author  xavierx
 */
public class Progreso extends javax.swing.JDialog {
    enc thumbails = new enc();
    /** Creates new form Progreso */
    public Progreso(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
    }
    
    public void procesarVector(Vector v, String dirActual){
        for (int i=0; i < v.size(); i++){
            int trabajoStatus = (100 * i)/ v.size();
            trabajoStatus(trabajoStatus);
            String s = (String) v.get(i);
            Image img = Toolkit.getDefaultToolkit().getImage(dirActual + File.separator + s);
            // Se utilzia un objeto MediaTracker para bloquear la tarea hasta
            // que la imagen se haya cargado o hayan transcurrido 10 segundos
            // desde que se inicia la carga
            MediaTracker tracker = new MediaTracker( this );
            tracker.addImage(img,1);
            try {
                if( !tracker.waitForID( 1,10000 ) ) {
                    System.out.println("Se ha superado el tiempo de carga de una imágen. Máximo 10 seg.");
                    System.exit( 1 );
                }//if
            }catch( InterruptedException e ) {
                System.out.println( e );
            }//try
            img = img.getScaledInstance(70, 40, 4);
            thumbails.make(dirActual+ File.separator + s,40, dirActual + File.separator + "thumbs", true);
        }//for
    }//procesarVector
    
    public void trabajoStatus(int lugar){
        trabajo.setValue(lugar);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        trabajo = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Activar Miniaturas");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        trabajo.setStringPainted(true);
        getContentPane().add(trabajo, java.awt.BorderLayout.SOUTH);

        jLabel1.setText("Generando Miniaturas. Un momento por favor...");
        getContentPane().add(jLabel1, java.awt.BorderLayout.NORTH);

        pack();
    }//GEN-END:initComponents
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new Progreso(new javax.swing.JFrame(), true).show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar trabajo;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    
}
