/*
 * splash.java
 *
 * Created on 24 de octubre de 2004, 15:01
 */

package xcx;

/**
 *
 * @author  xavierx
 */
public class splash extends javax.swing.JDialog {
    
    /** Creates new form splash */
    public splash(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    /*
    public void centrarFrame(JFrame frame) {
        Dimension tamanoPant=Toolkit.getDefaultToolkit().getScreenSize();
        Dimension tamanoFrame= frame.getSize();
        frame.setLocation((int)(tamanoPant.width-tamanoFrame.width)/2,(int)(tamanoPant.height-tamanoFrame.height)/2);
    }//centrarFrame
    */
    public void avanzar(int i){
        jProgressBar1.setValue(i);
    }//avanzar
    
    public void textoBarProgress(String text){
        jProgressBar1.setString(text);
    }//textoBarProgress
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setResizable(false);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jProgressBar1.setFont(new java.awt.Font("Default", 1, 12));
        jProgressBar1.setString("Cargando...");
        jProgressBar1.setStringPainted(true);
        getContentPane().add(jProgressBar1, java.awt.BorderLayout.SOUTH);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/xcx/kfirma.jpg")));
        getContentPane().add(jLabel1, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new splash(new javax.swing.JFrame(), true).show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    
}
